In [17]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
dish_df = pd.read_csv('./data/HCAT Data Set - Sheet2.csv')
rating_df = pd.read_csv('./data/HCAT Data Set - Rating 2.csv')

In [19]:
dish_df

,dish_id,category,name,ingredients,add_ons,preferred_weather,type,base_price,calories,Cooking Method,spice_level,allergens,available_days
0,1,Appetizers,Goose Cream Soup,"[""goose meat"", ""cream"", ""carrots"", ""celery"", ""...","[""goose giblets"", ""vegetables"", ""cress""]",Winter,Meat,15.5,150,Boiled,Low,"[""none""]",Monday to Friday
1,2,Appetizers,Goat Cheese,"[""goat cheese"", ""honey"", ""walnuts"", ""mixed gre...","[""goat cheese"", ""bacon"", ""onion cream"", ""pear""]",All Seasons,Vegetarian,18.5,200,Roasted,Low,"[""dairy""]",From 12:00 to 14:00
2,3,Appetizers,Vitello Tonnato,"[""veal"", ""tuna"", ""mayonnaise"", ""capers"", ""lemo...","[""tuna"", ""capers"", ""baby leaf""]",Summer,Meat,17.5,180,No Cook,Low,"[""seafood""]",Monday to Friday
3,4,Appetizers,Beef Tartare,"[""beef"", ""egg yolk"", ""mustard"", ""capers"", ""par...","[""corn"", ""coriander"", ""jalapenos"", ""papadam""]",Winter,Meat,18.5,220,No Cook,Medium,"[""none""]",Monday to Friday
4,5,Appetizers,Marinated Monkfish,"[""monkfish"", ""lemon juice"", ""olive oil"", ""garl...","[""radicchio"", ""saffron mayo"", ""white tomato fo...",Summer,Meat,17.5,170,Marinated,Low,"[""seafood""]",Monday to Friday
5,6,Appetizers,Salmon Rolls,"[""smoked salmon"", ""cream cheese"", ""dill"", ""lem...","[""salmon"", ""honey mustard sauce"", ""baby leaf""]",All Seasons,Meat,13.0,130,No Cook,Low,"[""seafood""]",Mon-Fri (12 PM to 2 PM)
6,7,Appetizers,Goat Cheese Patties,"[""goat cheese"", ""bread crumbs"", ""egg"", ""flour""...","[""fried onion cream"", ""berries"", ""greens""]",All Seasons,Vegetarian,15.5,160,Roasted,Low,"[""dairy""]",Mon-Fri (12 PM to 2 PM)
7,8,Appetizers,Pumpkin Soup,"[""pumpkin"", ""onions"", ""vegetable stock"", ""crea...","[""coconut"", ""apple"", ""pumpkin seeds"", ""pumpkin...",All Seasons,Vegetarian,12.5,150,Boiled,Low,"[""none""]",Mon-Fri (12 PM to 2 PM)
8,9,Main Courses,Beef Fillet,"[""beef fillet"", ""butter"", ""garlic"", ""rosemary""...","[""beef"", ""porcini mushroom"", ""chestnuts""]",All Seasons,Meat,39.5,400,Roasted,Medium,"[""none""]",All Days
9,10,Main Courses,Fish of the Day,"[""fish fillet"", ""lemon juice"", ""butter"", ""pars...","[""fish"", ""potato lime puree"", ""beetroot""]",Summer,Meat,35.5,350,Grilled,Low,"[""seafood""]",All Days
10,11,Main Courses,Ox Cheek,"[""ox cheeks"", ""red wine"", ""onions"", ""carrots"",...","[""beef"", ""ravioli"", ""pumpkin"", ""onions""]",Winter,Meat,35.5,370,Braised,Medium,"[""gluten""]",All Days
11,12,Main Courses,Duck Leg Confit,"[""duck legs"", ""duck fat"", ""garlic"", ""thyme"", ""...","[""duck"", ""kale"", ""potato dumplings"", ""grapefru...",Winter,Meat,35.5,360,Confit,Medium,"[""none""]",All Days
12,13,Main Courses,Risotto,"[""arborio rice"", ""onions"", ""butter"", ""parmesan...","[""roasted peppers"", ""chorizo"", ""parma ham""]",Summer,Meat,32.5,320,Boiled,Low,"[""dairy""]",All Days
13,14,Main Courses,Truffle Gnocchi,"[""potato gnocchi"", ""truffle oil"", ""parmesan ch...","[""onions"", ""tomatoes"", ""parmesan""]",All Seasons,Vegetarian,33.5,330,Boiled,Low,"[""dairy""]",All Days
14,15,Main Courses,Veal Liver,"[""veal liver"", ""onions"", ""butter"", ""flour"", ""s...","[""dried tomatoes"", ""raisins"", ""gnocchi""]",All Seasons,Meat,24.5,240,Pan-Fried,Medium,"[""gluten"", ""dairy""]",Mon-Fri (12 PM to 2 PM)
15,16,Main Courses,Fish of the Day,"[""fish fillet"", ""lime juice"", ""mashed potatoes...","[""lime mashed potatoes"", ""beetroot"", ""coconut ...",All Seasons,Meat,23.0,230,Grilled,Low,"[""seafood""]",Mon-Fri (12 PM to 2 PM)
16,17,Main Courses,Rump Steak Medium,"[""rump steak"", ""salt"", ""pepper"", ""olive oil"", ...","[""fried potatoes"", ""mixed salad"", ""jus""]",All Seasons,Meat,24.5,250,Grilled,Medium,"[""none""]",Mon-Fri (12 PM to 2 PM)
17,18,Main Courses,"Schnitzel ""Vienna Style""","[""veal or pork cutlet"", ""flour"", ""eggs"", ""brea...","[""cauliflower"", ""rosemary potatoes""]",All Seasons,Meat,21.5,220,Fried,Medium,"[""gluten"", ""dairy""]",Mon-Fri (12 PM to 2 PM)
18,19,Main Courses,Risotto,"[""arborio rice"", ""pumpkin"", ""picandou cheese"",...","[""pumpkin"", ""picandou"", ""parmesan""]",All Seasons,Vegetarian,21.0,210,Boiled,Low,"[""dairy""]",Mon-Fri (12 PM to 2 PM)
19,20,Main Courses,Pasta Carbonara,"[""spaghetti"", ""egg yolks"", ""pancetta"", ""parmes...","[""egg"", ""pancetta"", ""parmesan""]",All Seasons,Meat,21.0,210,Boiled,Low,"[""gluten"", ""dairy""]",Mon-Fri (12 PM to 2 PM)
20,21,Desserts,Nougat Tiramisu,"[""mascarpone"", ""nougat"", ""coffee"", ""ladyfinger...","[""nougat"", ""port wine pear"", ""pumpkin ice cream""]",All Seasons,Vegetarian,16.5,250,No Cook,Low,"[""dairy""]",All Days
21,22,Desserts,Poppy Seed and Curd Dumplings,"[""poppy seeds"", ""curd cheese"", ""flour"", ""eggs""...","[""spiced plums"", ""vanilla sauce"", ""sweet crumbs""]",Winter,Vegetarian,16.5,240,Boiled,Low,"[""dairy"", ""gluten""]",All Days
22,23,Desserts,Culinary Specialties Display,"[""cheddar cheese"", ""brie cheese"", ""salami"", ""p...","[""cheese board"", ""cold cuts""]",All Seasons,Vegetarian,16.5,300,No Cook,NaN,"[""dairy""]",All Days
23,24,Desserts,Dessert of the Day: 3-Course Menu,"[""seasonal dessert items"", ""optional beef ingr...","[""adjusted portions"", ""optional beef surcharge""]",All Seasons,Meat,10.5,350,Mixed Methods,Varies,"[""varies""]",Until 8:30 PM
24,25,Chef’s Choice,Culinary Specialties Display Case,"[""cheddar cheese"", ""brie cheese"", ""salami"", ""p...","[""cheese platter"", ""cold cuts""]",All Seasons,Vegetarian,16.5,160,No Cook,NaN,"[""dairy""]",Mon-Fri (12 PM to 2 PM)
25,26,Chef’s Choice,2-Course Lunch Menu,"[""starter ingredients"", ""main course ingredien...","[""appetizer"", ""main course""]",All Seasons,Vegetarian,34.0,600,Mixed Methods,Varies,"[""varies""]",Mon-Fri (12 PM to 2 PM)
26,27,Chef’s Choice,3-Course Menu,"[""starter ingredients"", ""main course ingredien...","[""adjusted portions"", ""optional beef surcharge""]",All Seasons,Vegetarian,66.0,800,Mixed Methods,Varies,"[""varies""]",Until 8:30 PM
27,28,Chef’s Choice,Vegetarian 3-Course Menu,"[""beetroot soup"", ""potato gnocchi"", ""yutu tart...","[""beetroot soup"", ""gnocchi"", ""yutu tarte""]",All Seasons,Vegetarian,39.0,750,Mixed Methods,Low,"[""dairy""]",All Days

In [20]:
dishes = list(dish_df['dish_id'])

In [21]:
rating_df

,User ID,Dish ID,Rating,Comments
0,1,2,5,"""Absolutely delicious, loved the flavor!"""
1,1,5,4,"""Fresh and tangy, enjoyable dish."""
2,1,13,3,"""Risotto was decent but lacked seasoning."""
3,2,3,4,"""Enjoyed the combination of flavors."""
4,2,13,5,"""Risotto was creamy and perfectly cooked!"""
5,2,15,4,"""Veal liver was tasty, loved the gnocchi."""
6,3,7,5,"""The cheese patties were divine!"""
7,3,15,3,"""Veal liver was overcooked, disappointed."""
8,3,8,4,"""Pumpkin soup was comforting and flavorful."""
9,4,4,5,"""Beef Tartare was prepared to perfection!"""
10,4,15,4,"""Loved the veal liver, perfectly tender."""
11,4,17,4,"""Rump steak was flavorful but slightly overdone."""
12,5,15,4,"""Delicious liver with a nice texture."""
13,5,18,5,"""Schnitzel was crunchy and satisfying."""
14,5,8,3,"""Soup lacked depth in flavor."""
15,6,15,5,"""The best veal liver I’ve had in ages!"""
16,6,20,4,"""Carbonara was rich and flavorful."""
17,6,18,4,"""Schnitzel was delightful."""
18,7,13,5,"""Risotto was the highlight of my meal!"""
19,7,17,4,"""Steak was juicy but could be seasoned more."""
20,7,20,4,"""Nice carbonara but slightly heavy."""
21,8,18,5,"""Schnitzel was cooked to perfection."""
22,8,15,4,"""Tender liver with great accompaniments."""
23,8,25,4,"""Lovely cheese platter, very fresh."""
24,9,25,3,"""Cheese platter was good but not exceptional."""
25,9,13,4,"""Risotto was creamy and delightful."""
26,9,3,4,"""Vitello Tonnato was refreshing."""
27,10,18,5,"""Schnitzel was crispy and flavorful."""
28,10,7,4,"""Cheese patties were satisfying."""
29,10,20,5,"""Carbonara was amazing, rich, and creamy!"""

In [22]:
ratings_matrix = rating_df.pivot(index='User ID', columns='Dish ID', values='Rating')
ratings_matrix

Dish ID   2    3    4    5    7    8    13   15   17   18   20   25
User ID
1        5.0  NaN  NaN  4.0  NaN  NaN  3.0  NaN  NaN  NaN  NaN  NaN
2        NaN  4.0  NaN  NaN  NaN  NaN  5.0  4.0  NaN  NaN  NaN  NaN
3        NaN  NaN  NaN  NaN  5.0  4.0  NaN  3.0  NaN  NaN  NaN  NaN
4        NaN  NaN  5.0  NaN  NaN  NaN  NaN  4.0  4.0  NaN  NaN  NaN
5        NaN  NaN  NaN  NaN  NaN  3.0  NaN  4.0  NaN  5.0  NaN  NaN
6        NaN  NaN  NaN  NaN  NaN  NaN  NaN  5.0  NaN  4.0  4.0  NaN
7        NaN  NaN  NaN  NaN  NaN  NaN  5.0  NaN  4.0  NaN  4.0  NaN
8        NaN  NaN  NaN  NaN  NaN  NaN  NaN  4.0  NaN  5.0  NaN  4.0
9        NaN  4.0  NaN  NaN  NaN  NaN  4.0  NaN  NaN  NaN  NaN  3.0
10       NaN  NaN  NaN  NaN  4.0  NaN  NaN  NaN  NaN  5.0  5.0  NaN

In [23]:
rated_dishes = list(rating_df['Dish ID'].unique())
unrated_dishes = [dish for dish in dishes if dish not in rated_dishes]
unrated_dishes

[1, 6, 9, 10, 11, 12, 14, 16, 19, 21, 22, 23, 24, 26, 27, 28]

In [24]:
new_columns = pd.DataFrame(np.nan, index=ratings_matrix.index, columns=unrated_dishes)
ratings_matrix = pd.concat([ratings_matrix, new_columns], axis=1)

In [25]:
ratings_matrix

,2,3,4,5,7,8,13,15,17,18,...,14,16,19,21,22,23,24,26,27,28
User ID,,,,,,,,,,,,,,,,,,,,,
1,5.0,NaN,NaN,4.0,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,4.0,NaN,NaN,NaN,NaN,5.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,5.0,4.0,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,5.0,NaN,NaN,NaN,NaN,4.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,3.0,NaN,4.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
ratings_matrix = ratings_matrix.fillna(0)
ratings_matrix

,2,3,4,5,7,8,13,15,17,18,...,14,16,19,21,22,23,24,26,27,28
User ID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,4.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,4.0,0.0,0.0,0.0,0.0,5.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,5.0,4.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,4.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
dishes_matrix = ratings_matrix.T
dishes_matrix

User ID   1    2    3    4    5    6    7    8    9    10
2        5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3        0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0
4        0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0
5        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7        0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0
8        0.0  0.0  4.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0
13       3.0  5.0  0.0  0.0  0.0  0.0  5.0  0.0  4.0  0.0
15       0.0  4.0  3.0  4.0  4.0  5.0  0.0  4.0  0.0  0.0
17       0.0  0.0  0.0  4.0  0.0  0.0  4.0  0.0  0.0  0.0
18       0.0  0.0  0.0  0.0  5.0  4.0  0.0  5.0  0.0  5.0
20       0.0  0.0  0.0  0.0  0.0  4.0  4.0  0.0  0.0  5.0
25       0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  3.0  0.0
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
11       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
16       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
19       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
21       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
22       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
23       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
24       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
26       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
27       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
28       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [28]:
cosine_sim = cosine_similarity(dishes_matrix)
cosine_sim_df = pd.DataFrame(cosine_sim, index=dishes_matrix.index, columns=dishes_matrix.index)
cosine_sim_df

,2,3,4,5,7,8,13,15,17,18,...,14,16,19,21,22,23,24,26,27,28
2,1.00000,0.000000,0.000000,1.00000,0.000000,0.000000,0.346410,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00000,1.000000,0.000000,0.00000,0.000000,0.000000,0.734847,0.285714,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.404061,0.707107,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.00000,0.000000,0.000000,1.00000,0.000000,0.000000,0.346410,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.00000,0.000000,0.000000,0.00000,1.000000,0.624695,0.000000,0.236639,0.000000,0.327429,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.00000,0.000000,0.000000,0.00000,0.624695,1.000000,0.000000,0.484873,0.000000,0.314485,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.34641,0.734847,0.000000,0.34641,0.000000,0.000000,1.000000,0.233285,0.408248,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.00000,0.285714,0.404061,0.00000,0.236639,0.484873,0.233285,1.000000,0.285714,0.635357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.00000,0.000000,0.707107,0.00000,0.000000,0.000000,0.408248,0.285714,1.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.00000,0.000000,0.000000,0.00000,0.327429,0.314485,0.000000,0.635357,0.000000,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.00000,0.000000,0.000000,0.00000,0.413714,0.000000,0.305888,0.267596,0.374634,0.569280,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.00000,0.424264,0.000000,0.00000,0.000000,0.000000,0.277128,0.323249,0.000000,0.419314,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:

N = 3  # Number of nearest neighbors (you can change this)

# Step 2: Create an empty matrix to store predicted ratings
predicted_ratings_matrix = ratings_matrix.copy()

# Step 3: Iterate over each user and each dish
for user in ratings_matrix.index:
    for dish in ratings_matrix.columns:
        # Only calculate for unrated dishes (where the rating is 0 or NaN)
        if ratings_matrix.at[user, dish] == 0:
            
            # Step 4: Get the similarities of the current dish with all other dishes
            similarities = cosine_sim_df[dish].drop(dish)  # Drop the self-similarity (diagonal)
            
            # Step 5: Find the top N most similar dishes that the user has rated
            rated_dishes = ratings_matrix.loc[user][ratings_matrix.loc[user] > 0]  # Dishes rated by the user
            similarities_rated_dishes = similarities[rated_dishes.index]  # Similarities to rated dishes
            
            # Step 6: Get the top N similar dishes
            top_n_similar_dishes = similarities_rated_dishes.nlargest(N)
            
            # Step 7: Calculate the weighted average for the prediction
            numerator = np.sum(top_n_similar_dishes * rated_dishes[top_n_similar_dishes.index])
            denominator = np.sum(np.abs(top_n_similar_dishes))
            
            # Step 8: Store the predicted rating
            if denominator != 0:  # Avoid division by zero
                predicted_ratings_matrix.at[user, dish] = numerator / denominator
            else:
                predicted_ratings_matrix.at[user, dish] = 0  # If no similar dishes, set prediction to 0 (or use another strategy)

# Step 9: Remove already-rated dishes (set them to NaN or 0)
for user in predicted_ratings_matrix.index:
    rated_dishes_by_user = ratings_matrix.loc[user][ratings_matrix.loc[user] > 0].index
    predicted_ratings_matrix.loc[user, rated_dishes_by_user] = np.nan  # or 0 if you prefer

# Display the predicted ratings matrix
predicted_ratings_matrix

,2,3,4,5,7,8,13,15,17,18,...,14,16,19,21,22,23,24,26,27,28
User ID,,,,,,,,,,,,,,,,,,,,,
1,NaN,3.0,0.0,NaN,0.000000,0.000000,NaN,3.000000,3.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,NaN,4.0,5.0,4.000000,4.000000,NaN,NaN,4.588286,4.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,3.0,3.0,0.0,NaN,NaN,3.000000,NaN,3.000000,3.758918,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,4.0,NaN,0.0,4.000000,4.000000,4.000000,NaN,NaN,4.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,4.0,4.0,0.0,3.749937,NaN,4.000000,NaN,4.000000,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,5.0,5.0,0.0,4.242016,4.606578,4.432672,NaN,4.432672,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,5.0,5.0,4.0,5.0,4.000000,0.000000,NaN,4.296575,NaN,4.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,4.0,4.0,0.0,4.580478,4.393422,4.000000,NaN,4.000000,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,4.0,NaN,0.0,4.0,0.000000,0.000000,NaN,3.616207,4.000000,3.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,NaN,4.334851,5.000000,4.792348,5.000000,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
recommendations = {}

for user in predicted_ratings_matrix.index:
    # Step 2: Filter dishes with predicted ratings > 0
    filtered_ratings = predicted_ratings_matrix.loc[user][predicted_ratings_matrix.loc[user] > 0]
    
    # Step 3: Sort ratings in descending order
    top_rated_items = filtered_ratings.sort_values(ascending=False)
    
    # Step 4: Select the top 3 dishes
    top_3_items = top_rated_items.head(3).index.tolist()
    
    # Step 5: Store the recommendations for each user
    recommendations[user] = top_3_items

# Display the recommendations
for user, items in recommendations.items():
    print(f"User {user}: Top 3 Recommended Dishes -> {items}")

User 1: Top 3 Recommended Dishes -> [15, 17, 20]
User 2: Top 3 Recommended Dishes -> [2, 5, 17]
User 3: Top 3 Recommended Dishes -> [20, 18, 3]
User 4: Top 3 Recommended Dishes -> [3, 7, 8]
User 5: Top 3 Recommended Dishes -> [20, 25, 3]
User 6: Top 3 Recommended Dishes -> [3, 4, 8]
User 7: Top 3 Recommended Dishes -> [2, 3, 5]
User 8: Top 3 Recommended Dishes -> [20, 7, 8]
User 9: Top 3 Recommended Dishes -> [2, 5, 17]
User 10: Top 3 Recommended Dishes -> [13, 17, 25]